jne_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
]

web/urls.py
from django.urls import path

from web.views import create_admission


app_name = 'web'
urlpatterns = [
    path('create-admission/', create_admission, name='form'),
]

web/models.py
from django.db import models


class AdmissionApplication(models.Model):
    full_name = models.CharField(max_length=128)
    email = models.EmailField()
    cap_id = models.IntegerField()
    selected_course = models.CharField(max_length=32)
    dob = models.DateField()
    gender = models.CharField(max_length=32)
    snumber = models.CharField(max_length=32)
    father_name = models.CharField(max_length=120)
    mother_name = models.CharField(max_length=120)
    parent_contact = models.CharField(max_length=32)
    institution = models.CharField(max_length=32)
    passout = models.CharField(max_length=32)
    course_plustwo = models.CharField(max_length=32)
    percentage_obtained = models.CharField(max_length=32)
    
    class Meta:
        verbose_name = "Admission"
        verbose_name_plural="Admission"
        db_table = "web_admission"

    def __str__(self):
        return self.full_name

web/forms.py
from django import forms

from web.models import AdmissionApplication


class AdmissionForm(forms.ModelForm):
    class Meta:
        model = AdmissionApplication
        fields = '__all__'

web/views.py
from django.shortcuts import render

from web.forms import AdmissionForm


#form registration
def create_admission(request):
    if request.method == "POST":
        form = AdmissionForm(request.POST)   

        if form.is_valid():
            form.save()
        else:
            print(form.errors.as_text)

        return render(request, 'form.html')

    else:
        return render(request, 'form.html')

templates/ba-english.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Department Of BA English</title>
    <meta name="keywords" content="jne, Jamia Nadwiyya, jamianadwiyyaartscollege, jne arts college, jne arts college edavanna,
     edavanna, jamia edavanna, jamiaedavanna, jamia edavanna, jnasc edavanna, 
     jneartscollege, jamia nadwiyya arts college, jamia nadwiyya arts college edavanna" />
    <meta
      name="description"
      content="In an era , when Muslim community along with other marginalized
      backward communities continued to exist in illiteracy and ignorance
      , Jamia Nadwiyya laid its foundation in 1964 by Kerala  Nadvathul
      Mujahideen (KNM) a socio- cultural – educational renaissance
      movement in Kerala ."
    />
    <meta
      property="og:description"
      content="In an era , when Muslim community along with other marginalized
      backward communities continued to exist in illiteracy and ignorance
      , Jamia Nadwiyya laid its foundation in 1964 by Kerala  Nadvathul
      Mujahideen (KNM) a socio- cultural – educational renaissance
      movement in Kerala ."
    />
    <meta property="og:title" content="JNE Arts College" />
    <meta property="og:image" sizes="16x16" content="./images/og-icon.png" type=”image/png” />

    <!-- links -->
    <link rel="stylesheet" href="./css/style.css" />
    <link rel="stylesheet" href="./css/all.css" />
    <link rel="stylesheet" href="./css/animate.css" />
    <link rel="stylesheet" href="./css/slick-theme.css" />
    <link rel="stylesheet" href="./css/slick.css" />
    <link rel="stylesheet" href="./css/owl.carousel.min.css" />
    <link rel="stylesheet" href="./css/owl.theme.default.min.css" />
    <script src="./js/jquery-min.js"></script>
    <script src="./js/wow.min.js"></script>
    <script src="./js/slick.min.js"></script>
    <script src="./js/owl.carousel.min.js"></script>
    <script src="./js/swiper-bundle.min.js"></script>
    <script src="./js/script.js"></script>
    <!-- favicon -->
    <link rel="icon" sizes="16x16" href="./images/jamia logo.png"
    type=”image/png”/>
  </head>
  <body>
    <header class="alter">
      <div class="wrapper">
        <h1 class="logo">
          <a href="index.html"><img src="./images/jamia logo.png" alt="Logo" /></a>
        </h1>
        <ul class="menu alter">
            <li class="active"><a href="index.html">Home</a></li>
            <li><a href="index.html#about">About Us</a></li>
            <li><a href="index.html#news">News</a></li>
            <li><a href="index.html#courses">Courses</a></li>
            <li><a href="index.html#gallery">Gallery</a></li>
            <li><a href="index.html#footer">Contact</a></li>
          </ul>
  
          <!-- mobile-menu -->
          <div class="hamburger">
              <span></span>
              <span></span>
              <span></span>
          </div>
          <div class="mobile-menu">
             <ul>
              <li class="active"><a href="index.html">Home</a></li>
              <li><a href="index.html#about">About Us</a></li>
              <li><a href="index.html#news">News</a></li>
              <li><a href="index.html#courses">Courses</a></li>
              <li><a href="index.html#gallery">Gallery</a></li>
              <li><a href="index.html#footer">Contact</a></li>
             </ul>
            <ul class="social-icons">
                <li>
                  <a href="#"><i class="fab fa-facebook"></i></a>
                </li>
                <li>
                  <a href=""><i class="fab fa-instagram"></i></a>
                </li>
                <li>
                  <a href=""><i class="fab fa-twitter"></i></a>
                </li>
              </ul>
          </div>
      </div>
    </header>
    <span class="overlay"></span>
    <section id="teachers">
      <div class="top">
        <h1>Department Of BA English</h1>
        <span>BACHELOR OF ARTS</span>
      </div>
      <div class="wrapper">
        <div class="hod">
          <div class="main">
            <div class="image-box">
              <img src="./images/Ba-shreejith.JPG" alt="Ba-shreejith" />
            </div>
            <div class="name">
              <h4>Shreejith M</h4>
              <span>HOD OF BA English</span>
            </div>
          </div>
          <div class="contact">
            <a href="tel:+919746402256">
              <small class="icon"><i class="fas fa-phone-alt"></i></small>
              <small>Contact</small>
            </a>
          </div>
        </div>
        <ul class="profiles">
          <li>
            <div class="image-box">
              <img src="./images/Ba-faheem.JPG" alt="Ba-faheem" />
            </div>
            <div class="name">
              <h4>Faheem M</h4>
              <span>TEACHER</span>
            </div>
          </li>
          <li>
            <div class="image-box">
              <img src="./images/Ba-iyaas.JPG" alt="Ba-iyyas" />
            </div>
            <div class="name">
              <h4>Iyyas Panoli</h4>
              <span>TEACHER</span>
            </div>
          </li>
          <li>
            <div class="image-box">
              <img src="./images/Ba-nadiya.JPG" alt="Ba-nadiyya" />
            </div>
            <div class="name">
              <h4>Nadiyya</h4>
              <span>TEACHER</span>
            </div>
          </li>
          <li>
            <div class="image-box">
              <img src="./images/Ba-shameel.JPG" alt="Ba-shameel" />
            </div>
            <div class="name">
              <h4>shameel V</h4>
              <span>TEACHER</span>
            </div>
          </li>
        </ul>
      </div>
    </section>
    <!-- main-section-end -->

    <footer id="footer">
        <div class="wrapper">
          <div class="top-container">
            <div class="logo">
              <h1>
                <a href="#home"
                  ><img src="./images/jamia logo.png" alt="Logo"
                /></a>
              </h1>
            </div>
            <div class="address-box">
                <div class="phone contact-item">
                  <a href="tel:04832704771">
                    <span><img src="./images/phone-icon.png" alt="Phone"></span></a>
                    <a href="tel:04832704771"><h4>0483 270 4771</h4></a>
                  </a>
                </div>
              <div class="location contact-item">
                <a href="https://goo.gl/maps/UvzzwmxHhgevra1q6 ">
                  <span><img src="./images/map-icon.png" alt="Map"></span></a>
                 <a href="https://goo.gl/maps/UvzzwmxHhgevra1q6 "> <h4>
                  Chempakuthu -Chalipadam-Kunduthodu Rd, Chembakuth, Edavanna,
                  Kerala 676123
                </h4></a>
                </a>
              </div>
              <div class="mail contact-item">
                <a href="#">
                  <span><img src="./images/mail-icon.png" alt="Mail"></span></a>
                 <a href=""><h4>hello@jamia.com</h4></a> 
                </a>
              </div>
            </div>
          </div>
          <ul class="social-icons">
            <li>
              <a href="#"><i class="fab fa-facebook"></i></a>
            </li>
            <li>
              <a href=""><i class="fab fa-instagram"></i></a>
            </li>
            <li>
              <a href=""><i class="fab fa-twitter"></i></a>
            </li>
          </ul>
          <div class="copy-text">
            <p>
              &copy; All Right Reserved | Design And Developed By BCA (2020 -
              2023).
            </p>
          </div>
        </div>
      </footer>
      <!-- footer-end -->
  </body>
</html>

templates/bca.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Department Of BCA</title>
    <meta name="keywords" content="jne, Jamia Nadwiyya, jamianadwiyyaartscollege, jne arts college, jne arts college edavanna,
     edavanna, jamia edavanna, jamiaedavanna, jamia edavanna, jnasc edavanna, 
     jneartscollege, jamia nadwiyya arts college, jamia nadwiyya arts college edavanna" />
    <meta
      name="description"
      content="In an era , when Muslim community along with other marginalized
      backward communities continued to exist in illiteracy and ignorance
      , Jamia Nadwiyya laid its foundation in 1964 by Kerala  Nadvathul
      Mujahideen (KNM) a socio- cultural – educational renaissance
      movement in Kerala ."
    />
    <meta
      property="og:description"
      content="In an era , when Muslim community along with other marginalized
      backward communities continued to exist in illiteracy and ignorance
      , Jamia Nadwiyya laid its foundation in 1964 by Kerala  Nadvathul
      Mujahideen (KNM) a socio- cultural – educational renaissance
      movement in Kerala ."
    />
    <meta property="og:title" content="JNE Arts College" />
    <meta property="og:image" sizes="16x16" content="./images/og-icon.png" type=”image/png” />

    <!-- links -->
    <link rel="stylesheet" href="./css/style.css" />
    <link rel="stylesheet" href="./css/all.css" />
    <link rel="stylesheet" href="./css/animate.css" />
    <link rel="stylesheet" href="./css/slick-theme.css" />
    <link rel="stylesheet" href="./css/slick.css" />
    <link rel="stylesheet" href="./css/owl.carousel.min.css" />
    <link rel="stylesheet" href="./css/owl.theme.default.min.css" />
    <script src="./js/jquery-min.js"></script>
    <script src="./js/wow.min.js"></script>
    <script src="./js/slick.min.js"></script>
    <script src="./js/owl.carousel.min.js"></script>
    <script src="./js/swiper-bundle.min.js"></script>
    <script src="./js/script.js"></script>
    <!-- favicon -->
    <link rel="icon" sizes="16x16" href="./images/jamia logo.png"
    type=”image/png”/>
  </head>
  <body>
    <header class="alter">
      <div class="wrapper">
        <h1 class="logo">
          <a href="index.html"><img src="./images/jamia logo.png" alt="Logo" /></a>
        </h1>
        <ul class="menu alter">
          <li class="active"><a href="index.html">Home</a></li>
          <li><a href="index.html#about">About Us</a></li>
          <li><a href="index.html#news">News</a></li>
          <li><a href="index.html#courses">Courses</a></li>
          <li><a href="index.html#gallery">Gallery</a></li>
          <li><a href="index.html#footer">Contact</a></li>
        </ul>

        <!-- mobile-menu -->
        <div class="hamburger">
            <span></span>
            <span></span>
            <span></span>
        </div>
        <div class="mobile-menu">
           <ul>
            <li class="active"><a href="index.html">Home</a></li>
            <li><a href="index.html#about">About Us</a></li>
            <li><a href="index.html#news">News</a></li>
            <li><a href="index.html#courses">Courses</a></li>
            <li><a href="index.html#gallery">Gallery</a></li>
            <li><a href="index.html#footer">Contact</a></li>
           </ul>
            <ul class="social-icons">
                <li>
                  <a href="#"><i class="fab fa-facebook"></i></a>
                </li>
                <li>
                  <a href=""><i class="fab fa-instagram"></i></a>
                </li>
                <li>
                  <a href=""><i class="fab fa-twitter"></i></a>
                </li>
              </ul>
          </div>
      </div>
    </header>
    <span class="overlay"></span>
    <section id="teachers">
      <div class="top">
        <h1>Department Of BCA</h1>
        <span>BACHELOR OF COMPUTER APPLICATION</span>
      </div>
      <div class="wrapper">
        <div class="hod">
          <div class="main">
            <div class="image-box">
              <img src="./images/Bca-faisal.JPG" alt="Bca-faisal" />
            </div>
            <div class="name">
              <h4>Faizal K.S</h4>
              <span>HOD OF BCA</span>
            </div>
          </div>
          <div class="contact">
            <a href="tel:+919895470067">
              <small class="icon"><i class="fas fa-phone-alt"></i></small>
              <small>Contact</small>
            </a>
          </div>
        </div>
        <ul class="profiles">
          <li>
            <div class="image-box">
              <img src="./images/Bca-mufeeda.JPG" alt="Bca-mufeeda" />
            </div>
            <div class="name">
              <h4>Mufeeda K</h4>
              <span>TEACHER</span>
            </div>
          </li>
          <li>
            <div class="image-box">
              <img src="./images/Bca-salim.JPG" alt="Bca-salim" />
            </div>
            <div class="name">
              <h4>Muhammed Salim C.T</h4>
              <span>TEACHER</span>
            </div>
          </li>
          <li>
            <div class="image-box">
              <img src="./images/Bca-vidya.jpg" alt="Bca-vidya" />
            </div>
            <div class="name">
              <h4>Vidya Rakesh</h4>
              <span>TEACHER</span>
            </div>
          </li>
          <li>
            <div class="image-box">
              <img src="./images/Bca-shifana.jpg" alt="Bca-shifana" />
            </div>
            <div class="name">
              <h4>Shifana K.P</h4>
              <span>TEACHER</span>
            </div>
          </li>
        </ul>
      </div>
    </section>
    <!-- main-section-end -->

    <footer id="footer">
        <div class="wrapper">
          <div class="top-container">
            <div class="logo">
              <h1>
                <a href="#home"
                  ><img src="./images/jamia logo.png" alt="Logo"
                /></a>
              </h1>
            </div>
            <div class="address-box">
                <div class="phone contact-item">
                  <a href="tel:04832704771">
                    <span><img src="./images/phone-icon.png" alt="Phone"></span></a>
                    <a href="tel:04832704771"><h4>0483 270 4771</h4></a>
                  </a>
                </div>
              <div class="location contact-item">
                <a href="https://goo.gl/maps/UvzzwmxHhgevra1q6 ">
                  <span><img src="./images/map-icon.png" alt="Map"></span></a>
                 <a href="https://goo.gl/maps/UvzzwmxHhgevra1q6 "> <h4>
                  Chempakuthu -Chalipadam-Kunduthodu Rd, Chembakuth, Edavanna,
                  Kerala 676123
                </h4></a>
                </a>
              </div>
              <div class="mail contact-item">
                <a href="#">
                  <span><img src="./images/mail-icon.png" alt="Mail"></span></a>
                 <a href=""><h4>hello@jamia.com</h4></a> 
                </a>
              </div>
            </div>
          </div>
          <ul class="social-icons">
            <li>
              <a href="#"><i class="fab fa-facebook"></i></a>
            </li>
            <li>
              <a href=""><i class="fab fa-instagram"></i></a>
            </li>
            <li>
              <a href=""><i class="fab fa-twitter"></i></a>
            </li>
          </ul>
          <div class="copy-text">
            <p>
              &copy; All Right Reserved | Design And Developed By BCA (2020 -
              2023).
            </p>
          </div>
        </div>
      </footer>
      <!-- footer-end -->
  </body>
</html>

templates/form.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>JNE - Enquiry Form</title>
    <meta name="keywords" content="jne, Jamia Nadwiyya, jamianadwiyyaartscollege, jne arts college, jne arts college edavanna,
         edavanna, jamia edavanna, jamiaedavanna, jamia edavanna, jnasc edavanna, 
         jneartscollege, jamia nadwiyya arts college, jamia nadwiyya arts college edavanna" />
    <meta name="description" content="In an era , when Muslim community along with other marginalized
          backward communities continued to exist in illiteracy and ignorance
          , Jamia Nadwiyya laid its foundation in 1964 by Kerala  Nadvathul
          Mujahideen (KNM) a socio- cultural – educational renaissance
          movement in Kerala ." />
    <meta property="og:description" content="In an era , when Muslim community along with other marginalized
          backward communities continued to exist in illiteracy and ignorance
          , Jamia Nadwiyya laid its foundation in 1964 by Kerala  Nadvathul
          Mujahideen (KNM) a socio- cultural – educational renaissance
          movement in Kerala ." />
    <meta property="og:title" content="JNE Arts College" />
    <meta property="og:image" sizes="16x16" content={% static "images/og-icon.png" %} type=”image/png” />

    <!-- links -->
    <link rel="stylesheet" href={% static "css/style.css" %} />
    <link rel="stylesheet" href={% static "css/all.css" %} />
    <link rel="stylesheet" href={% static "css/aos.css" %}>
    <link rel="stylesheet" href={% static "css/slick-theme.css" %} />
    <link rel="stylesheet" href={% static "css/slick.css" %} />
    <link rel="stylesheet" href={% static "css/owl.carousel.min.css" %} />
    <link rel="stylesheet" href={% static "css/owl.theme.default.min.css" %} />
    <link rel="stylesheet" href={% static "css/swiper-bundle.min.css" %} />
    <link rel="stylesheet" href={% static "css/sweetalert2.min.css" %}>
    <script src={% static "js/jquery-min.js"%}></script>
    <script src={% static "js/aos.js"%}></script>
    <script src={% static "js/slick.min.js"%}></script>
    <script src={% static "js/owl.carousel.min.js"%}></script>
    <script src={% static "js/swiper-bundle.min.js"%}></script>
    <script src={% static "js/multi-animated-counter.js"%}></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src={% static "js/script.js"%} defer></script>
    <!-- favicon -->
    <link rel="icon" sizes="16x16" href={% static "images/jamia logo.png"%} type=”image/png” />
</head>
<body>
    <header class="alter">
        <div class="wrapper">
            <h1 class="logo">
                <a href="index.html"><img src={% static "images/jamia logo.png"%} alt="Logo" /></a>
            </h1>
            <ul class="menu alter">
                <li class="active"><a href="index.html">Home</a></li>
                <li><a href="index.html#about">About Us</a></li>
                <li><a href="index.html#news">News</a></li>
                <li><a href="index.html#courses">Courses</a></li>
                <li><a href="index.html#gallery">Gallery</a></li>
                <li><a href="index.html#footer">Contact</a></li>
            </ul>

            <!-- mobile-menu -->
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="mobile-menu">
                <ul>
                    <li class="active"><a href="index.html">Home</a></li>
                    <li><a href="index.html#about">About Us</a></li>
                    <li><a href="index.html#news">News</a></li>
                    <li><a href="index.html#courses">Courses</a></li>
                    <li><a href="index.html#gallery">Gallery</a></li>
                    <li><a href="index.html#footer">Contact</a></li>
                </ul>
                <ul class="social-icons">
                    <li>
                        <a href="#"><i class="fab fa-facebook"></i></a>
                    </li>
                    <li>
                        <a href=""><i class="fab fa-instagram"></i></a>
                    </li>
                    <li>
                        <a href=""><i class="fab fa-twitter"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <section id="form">
        <div class="wrapper">
            <div class="head">
                <h2>JNE Arts College</h2>
                <h4>APPLICATION FORM FOR ADMISSION TO DEGREE/ PG COURSE</h4>
            </div>
            <div class="container" id="container">
                <form method="post" action={% url 'web:form' %} >
                    {% csrf_token %}
                    <div class="item">
                        <label for="fullname">Full Name </label>
                        <input type="text" placeholder="Enter Full Name" required  id="name" name="full_name"  />
                    </div>
                    <div class="item">
                        <label for="email">E-Mail </label>
                        <input type="email" placeholder="Enter e-mail" required id="email" name="email" />
                    </div>
                    <div class="item">
                        <label for="id">CAP ID</label>
                        <input type="text" placeholder="Enter CAP ID" id="id" required name="cap_id"  />
                    </div>
                    <div class="item">
                        <label for="course">Select Courses</label>
                        <select name="selected_course" placeholder="Course" required id="course" required>
                            <option value="BBA">BBA</option>
                            <option value="BCA">BCA</option>
                            <option value="BCOM">BCOM</option>
                            <option value="BA-English">BA-English</option>
                            <option value="BSC-Physics">BSC-Physics</option>
                            <option value="Mcom">M.com</option>
                            <option value="Msc-Physics">M.sc-Physics</option>
                        </select>
                    </div>
                    <div class="item">
                        <label for="dob">Date Of Birth</label>
                        <input type="date" placeholder="date of birth" id="dob" name="dob" required />
                    </div>
                    <div class="item">
                        <label for="gender">Gender</label>
                        <select name="gender" placeholder="Gender" required required id="gender">
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                            <option value="other">other</option>
                        </select>
                    </div>
                    <div class="item">
                        <label for="snumber">Mobile Number Of Student</label>
                        <input type="tel"  placeholder="Mobile Number" id="snumber" name="snumber" required 
                            maxlength="10" />
                    </div>
                    <div class="item">
                        <label for="name-father">Name of Father</label>
                        <input type="text" placeholder="Name of Father" id="name-father" name="father_name" required
                             />
                    </div>
                    <div class="item">
                        <label for="name-mother">Name of Mother</label>
                        <input type="text" placeholder="name of Mother" id="name-mother" name="mother_name" required
                             />
                    </div>
                    <div class="item">
                        <label for="number-parent">Contact Number of Parent</label>
                        <input type="tel"  placeholder="Mobile Number" id="number-parent" name="parent_contact" required
                             maxlength="10">
                    </div>
                    <div class="item">
                        <label for="institution">Institution last attended</label>
                        <input type="text" placeholder="Institution last attended" id="institution" name="institution"
                             required />
                    </div>
                    <div class="item">
                        <label for="passout">Month and Year Of Passing</label>
                        <input type="tel"  placeholder="Month and Year Of Passing" id="passout" name="passout" required />
                    </div>
                    <div class="item">
                        <label for="course">Course Selected for Plus Two</label>
                        <input type="text" placeholder="eg: science" id="mark" name="course_plustwo" required  />
                    </div>
                    <div class="item">
                        <label for="percentage">Percentage obtained</label>
                        <input type="text" placeholder="Percentage obtained" id="percentage" name="percentage_obtained" required
                             maxlength="4" />
                    </div>
                    <input class="submit" type="submit" value="Submit" id="button-submit" onclick=formHandle() />
                </form>
            </div>
        </div>
    </section>
    <footer id="footer">
        <div class="wrapper">
            <div class="top-container">
                <div class="logo">
                    <h1>
                        <a href="#home"><img src={% static "images/jamia logo.png"%} alt="Logo" /></a>
                    </h1>
                </div>
                <div class="address-box">
                    <div class="phone contact-item">
                        <a href="tel:04832704771">
                            <span><img src={% static "images/phone-icon.png"%} alt="Phone"></span></a>
                        <a href="tel:04832704771">
                            <h4>0483 270 4771</h4>
                        </a>
                        </a>
                    </div>
                    <div class="location contact-item">
                        <a href="https://goo.gl/maps/UvzzwmxHhgevra1q6 ">
                            <span><img src={% static "images/map-icon.png"%} alt="Map"></span></a>
                        <a href="https://goo.gl/maps/UvzzwmxHhgevra1q6 ">
                            <h4>
                                Chempakuthu -Chalipadam-Kunduthodu Rd, Chembakuth, Edavanna,
                                Kerala 676123
                            </h4>
                        </a>
                        </a>
                    </div>
                    <div class="mail contact-item">
                        <a href="#">
                            <span><img src={% static "images/mail-icon.png"%} alt="Mail"></span></a>
                        <a href="">
                            <h4>hello@jamia.com</h4>
                        </a>
                        </a>
                    </div>
                </div>
            </div>
            <ul class="social-icons">
                <li>
                    <a href="#"><i class="fab fa-facebook"></i></a>
                </li>
                <li>
                    <a href=""><i class="fab fa-instagram"></i></a>
                </li>
                <li>
                    <a href=""><i class="fab fa-twitter"></i></a>
                </li>
            </ul>
            <div class="copy-text">
                <p>
                    &copy; All Right Reserved | Design And Developed By <span>BCA (2020 -
                        2023).</span>
                </p>
            </div>
        </div>
    </footer>
</body>

</html>